#spring.application.name=demo1

spring:
  application:
    name: demo1
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id:
            client-secret:
            provider:
            authorization-grant-type:
            redirect-uri:
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://localhost:8080
